[programs.localnet]
solana_twitter = "FZgmTU17iccnK5EiDfubA1Jw7qB1bwce5vefk5S7eTm6"

[programs.devnet]
solana_twitter = "FZgmTU17iccnK5EiDfubA1Jw7qB1bwce5vefk5S7eTm6"

[programs.mainnet]
solana_twitter = "FZgmTU17iccnK5EiDfubA1Jw7qB1bwce5vefk5S7eTm6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/loris/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
